config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { passwords: :passwords }

  devise_scope :user do

    get '/users/slack_callback' => 'sessions#slack_callback'

    authenticated :user do
      root 'dashboard#index'
    end
    unauthenticated :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  resources :interviewees, except: [:destroy], concerns: [:paginatable] do
    resources :activities, only: [:index, :create]

    member do
      get :print
    end

    collection do
      get :result
      get :calendar
    end
  end

  resources :positions, except: [:show]
  resources :dashboard, only: [:index]
  resource :user, only: [:edit, :update]

  scope 'pre-interview', controller: 'pre_interview', as: 'pre_interview' do
    get 'consent/', action: :consent, as: 'consent'
    get 'new/', action: :new, as: 'new'
    post 'create/', action: 'create', as: 'create'
    get 'complete', action: 'complete', as: 'complete'
  end

end

app/controllers/pre_interview_controller.rb
class PreInterviewController < ApplicationController

  layout 'interviewee'

  rescue_from ActiveRecord::RecordNotFound, with: :handle_record_not_found

  # 同意書
  def consent

  end

  def new
    @interviewee = Interviewee.new
    @interviewee.build_all_relations
  end

  def create

    begin

      @interviewee = Interviewee.new interviewee_params.merge(finish_edit: true)
      @interviewee.save!

      redirect_to url_for(action: :complete)

    rescue Exception => e
      flash.now[:alert] = e.message
      @interviewee.build_all_relations
      render :new
    end

  end

  def complete
    
  end

  private

  def set_interviewee
    @interviewee = Interviewee.find_by! token: params[:token], finish_edit: false
  end

  def interviewee_params
    params.require(:interviewee)
      .permit(:name, :name_en, :gender, :birthday, :position_id, :native_place, :id_number, :blood_type, :communicate_address,
              :communicate_phone, :residence_address, :residence_phone, :email, :phone, :over_time, :marriage, :military, :relatives,
              :expertise, :hobby, :health, :genetic_disease, :genetic_disease_note, :nociceptive_disease,
              :nociceptive_disease_note, :other_disease, :other_disease_note, :chinese, :taiwanese, :hakka, :english,
              :japanese, :onboard_date, :wish_salary, :other_language_familiar, :other_language_unfamiliar,
              educations_attributes: [:id, :name, :department, :graduated, :school_type],
              experiences_attributes: [:id, :name, :title, :period, :seniority, :salary, :reason],
              families_attributes: [:id, :title, :name, :job],
              supervisors_attributes: [:id, :name, :department, :title, :phone, :contact_time]
      )
  end

  def handle_record_not_found
    raise ActionController::RoutingError.new('已填寫完畢，或找不到資料')
  end

end

app/helpers/pre_interview_helper.rb
module PreInterviewHelper
end

app/views/pre_interview/_consent.html.slim
h2.text-center 風尚數位科技股份有限公司

h4.text-center 個人資料告知事項暨同意書

p 本公司依據個人資料保護法（以下稱個資法）第 8 條第 1 項之規定，向您告知本公司對於您填寫之本份「人事資料表」中有關個人資料之蒐集，處理及利用等各款事項如下，請您務必詳閱：

p 一、蒐集目的與方式

ol
  li 目的：作為招募或人事行政管理相關業務之用。
  li 方式：本公司利用本份人事資料表進行您個人資料之蒐集。若於後續個人資料有任何異動，請主動向本公司人力資源單位申請更新，以保持資料正確性。

p 二、蒐集之個人資料類別：姓名（中英文）、出生日期、身份證統一編號、血型、連絡方式（包括但不限於電話號碼、E-MAIL或地址）、照片、性別、婚姻、有無子女或其他得以直接或間接識別您之個人資料。

p  三、利用期間、地區、對象及方式

ol
  li 期間：經錄取為正式員工後，本份文件將轉為本公司員工人事資料表，並於本公司營運期間繼續保存；若於面談後未經錄取或錄取未報到者，本公司政策將保留本份文件之個人資料一年。
  li 地區：台灣地區
  li 利用對象：本公司人力資源單位同仁及與招募或管理相關之主管人員。
  li 利用方式：以人事行政相關作業之利用。

p 四、個人資料之權利

p 您可依個人資料保護法，就您的個人資料像本公司人力資源單位做以下請求，本公司並得酌收必要成本費用。

ol
  li 查詢或請求閱覽
  li 請求製給複製本
  li 請求補充或更正，但您應為適當之釋明。
  li 請求停止蒐集、處理或利用及請求刪除，惟依法本公司因執行業務或法令所必須者，得不依您的請求為之。

p 五、本公司將嚴密保護您的個人資料含通訊方式，絕不會以販賣等方式透露給第三者，且本公司將遵守個人資料保護法之規定，妥善保存您的個人資料。

p 六、您得自由選擇是否針對本份文件所要求之各欄位提供個人資料，惟若拒絕提供相關必要之個人資料，本公司將無法進行必要之審核作業，可能會對應徵申請的處理及結果有所影響。

p 七、若您明知屬於錯誤不實或具誤導性之資料而仍提供本公司，經本公司查驗屬實，本公司將取消錄取資格或於聘僱後解僱。

p 八、立同意書人同意本公司前述告知事項，並同意本公司於本公司之子公司/分公司及關係企業間蒐集、處理及利用或國際傳輸立同意書人之個人資料。

p 此致

p 風尚數位科技股份有限公司

app/views/pre_interview/_education.html.slim
.panel.panel-default.margin-top-10
  .panel-heading.font-normal
    | 學歷
  .panel-body.font-normal
    table.table.table-bordered#education-table
      thead
        tr
          th 學校名稱
          th 科系
          th 畢業
          th 日（夜）間
      tbody
        = f.fields_for :educations, wrapper: false do |ff|
          tr.fields
            td
              = ff.hidden_field :id
              = ff.text_field :name, class: 'form-control'
            td = ff.text_field :department, class: 'form-control'
            td[style="vertical-align: middle"]
              .checkbox[style="padding: 0"]
                label
                  = ff.check_box :graduated
            td
              - Education.school_types.each do |school_type|
                .radio.radio-inline
                  label
                    = ff.radio_button :school_type, school_type.first,
                            {checked: ff.object.school_type.to_s == school_type.first.to_s}
                    = t "enums.education.school_type.#{school_type.first}"

    = f.link_to_add :educations, class: 'btn btn-sm btn-primary', data: {target: "#education-table"} do
      = fa_icon('plus')

app/views/pre_interview/_experience.html.slim
.panel.panel-default.margin-top-10
  .panel-heading.font-normal
    | 經歷
  .panel-body.font-normal
    table.table.table-bordered#experience-table
      thead
        tr
          th[style="width: 200px"] 公司名稱
          th[style="width: 120px"] 職稱
          th[style="width: 150px"] 任職期間
          th[style="width: 120px"] 年資
          th[style="width: 120px"] 薪資
          th 離職原因
      tbody
        = f.fields_for :experiences, wrapper: false do |ff|
          tr.fields
            th
              = ff.hidden_field :id
              = ff.text_field :name, class: 'form-control'
            th = ff.text_field :title, class: 'form-control'
            th = ff.text_field :period, class: 'form-control'
            th = ff.text_field :seniority, class: 'form-control'
            th = ff.text_field :salary, class: 'form-control'
            th = ff.text_field :reason, class: 'form-control'

    = f.link_to_add :experiences, class: 'btn btn-sm btn-primary', data: {target: "#experience-table"} do
      = fa_icon('plus')

app/views/pre_interview/_family.html.slim
.panel.panel-default.margin-top-10
  .panel-heading.font-normal
    | 家庭狀況
  .panel-body.font-normal
    table.table.table-bordered#family-table
      thead
        tr
          th 稱謂
          th 姓名
          th 職業或就讀學校
      tbody
        = f.fields_for :families, wrapper: false do |ff|
          tr.fields
            td
              = ff.hidden_field :id
              = ff.text_field :title, class: 'form-control'
            td = ff.text_field :name, class: 'form-control'
            td = ff.text_field :job, class: 'form-control'

    = f.link_to_add :families, class: 'btn btn-sm btn-primary', data: {target: "#family-table"} do
      = fa_icon('plus')

app/views/pre_interview/_form.html.slim
= render partial: 'pre_interview/personal', locals: {f: f, disabled: disabled}

= render partial: 'pre_interview/education', locals: {f: f}

= render partial: 'pre_interview/experience', locals: {f: f}

= render partial: 'pre_interview/family', locals: {f: f}

= render partial: 'pre_interview/health', locals: {f: f}

= render partial: 'pre_interview/language', locals: {f: f}

= render partial: 'pre_interview/supervisor', locals: {f: f}

= render partial: 'pre_interview/last_part', locals: {f: f}

javascript:
  $(function () {
      $(window).on('nested:fieldAdded', function () {
          $.material.init();
      });

      $("#interviewee_birthday").datepicker({
          format: 'yyyy-mm-dd',
          language: 'zh-TW',
          startView: "decade"
      });
  });

  window.NestedFormEvents.prototype.insertFields = function (content, assoc, link) {
      var $tr = $($(link).data('target')).find('tr:last'),
          $content = $(content);
      return $content.insertAfter($tr);
  };

app/views/pre_interview/_health.html.slim
.panel.panel-default.margin-top-10
  .panel-heading.font-normal
    | 健康狀況
  .panel-body.font-normal
    p 過去是否有重大疾病

    .row
      .col-md-12
        .checkbox
          label
            = f.check_box :health
            |  否

    .row
      .col-md-12
        .checkbox
          label
            = f.check_box :genetic_disease
            |  遺傳性疾病
        = f.text_field :genetic_disease_note, class: 'form-control'

    .row
      .col-md-12
        .checkbox
          label
            = f.check_box :nociceptive_disease
            |  傷害性疾病
        = f.text_field :nociceptive_disease_note, class: 'form-control'

    .row
      .col-md-12
        .checkbox
          label
            = f.check_box :other_disease
            |  其他
        = f.text_field :other_disease_note, class: 'form-control'

app/views/pre_interview/_language.html.slim
.panel.panel-default.margin-top-10
  .panel-heading.font-normal
    | 語言能力
  .panel-body.font-normal
    table.table.table-bordered
      tr
        td 略懂
        td
          .radio.radio-inline
            label
              = f.radio_button :chinese, 0, {checked: f.object.chinese == 0}
              | 國語

        td
          .radio.radio-inline
            label
              = f.radio_button :taiwanese, 0, {checked: f.object.taiwanese == 0}
              | 台語

        td
          .radio.radio-inline
            label
              = f.radio_button :hakka, 0, {checked: f.object.hakka == 0}
              | 客家語

        td
          .radio.radio-inline
            label
              = f.radio_button :english, 0, {checked: f.object.english == 0}
              | 英文

        td
          .radio.radio-inline
            label
              = f.radio_button :japanese, 0, {checked: f.object.japanese == 0}
              | 日文

        td
          = f.text_field :other_language_unfamiliar, class: 'form-control', placeholder: '其他'

      tr
        td 精通
        td
          .radio.radio-inline
            label
              = f.radio_button :chinese, 1, {checked: f.object.chinese == 1}
              | 國語

        td
          .radio.radio-inline
            label
              = f.radio_button :taiwanese, 1, {checked: f.object.taiwanese == 1}
              | 台語

        td
          .radio.radio-inline
            label
              = f.radio_button :hakka, 1, {checked: f.object.hakka == 1}
              | 客家語

        td
          .radio.radio-inline
            label
              = f.radio_button :english, 1, {checked: f.object.english == 1}
              | 英文

        td
          .radio.radio-inline
            label
              = f.radio_button :japanese, 1, {checked: f.object.japanese == 1}
              | 日文

        td
          = f.text_field :other_language_familiar, class: 'form-control', placeholder: '其他'

app/views/pre_interview/_last_part.html.slim
.panel.panel-default.margin-top-10
  .panel-body.font-normal
    .form-group
      label.col-sm-2.control-label
        | 可到職日
      .col-sm-10
        = f.text_field :onboard_date, class: 'form-control datepicker'

    .form-group
      label.col-sm-2.control-label
        | 希望待遇
      .col-sm-10
        = f.text_field :wish_salary, class: 'form-control'

app/views/pre_interview/_personal.html.slim
.panel.panel-default.margin-top-10
  .panel-heading.font-normal
    | 基本資料
  .panel-body.font-normal

    .form-group
      label.col-sm-2.control-label
        | 姓名（中文）

      .col-sm-10
        = f.text_field :name, class: 'form-control'

    .form-group
      label.col-sm-2.control-label
        | 姓名（英文）

      .col-sm-10
        = f.text_field :name_en, class: 'form-control'

    .form-group
      label.col-sm-2.control-label
        | 性別

      .col-sm-4
        - Interviewee.genders.each do |i|
          .radio.radio-inline
            label
              = f.radio_button :gender, i.first, checked: f.object.gender == i.first
              = gender(i.second)

    .form-group
      label.col-sm-2.control-label
        | 應徵項目

      .col-sm-10
        = f.collection_select :position_id, Position.all, :id, :name, {}, class: 'form-control'

    .form-group
      label.col-sm-2.control-label
        | 出生日期

      .col-sm-10
        = f.text_field :birthday, class: 'form-control'

    .form-group
      label.col-sm-2.control-label
        | 籍貫

      .col-sm-10
        = f.text_field :native_place, class: 'form-control'

    .form-group
      label.col-sm-2.control-label
        | 身份證號碼

      .col-sm-10
        = f.text_field :id_number, class: 'form-control'

    .form-group
      label.col-sm-2.control-label
        | 血型

      .col-sm-10
        = f.text_field :blood_type, class: 'form-control'

    .form-group
      label.col-sm-2.control-label
        | 通訊地址

      .col-sm-4
        = f.text_field :communicate_address, class: 'form-control'

      label.col-sm-2.control-label
        | 電話

      .col-sm-4
        = f.text_field :communicate_phone, class: 'form-control'

    .form-group
      label.col-sm-2.control-label
        | 戶籍地址

      .col-sm-4
        = f.text_field :residence_address, class: 'form-control'

      label.col-sm-2.control-label
        | 電話

      .col-sm-4
        = f.text_field :residence_phone, class: 'form-control'

    .form-group
      label.col-sm-2.control-label
        | Email

      .col-sm-10
        = f.text_field :email, class: 'form-control'

    .form-group
      label.col-sm-2.control-label
        | 行動電話

      .col-sm-10
        = f.text_field :phone, class: 'form-control'

    .form-group
      label.col-sm-2.control-label
        | 加班

      .col-sm-10
        .radio.radio-inline
          label
            = f.radio_button :over_time, 1, {checked: f.object.over_time == true}
            | 可
        .radio.radio-inline
          label
            = f.radio_button :over_time, 0, {checked: f.object.over_time == false}
            | 否

    .form-group
      label.col-sm-2.control-label
        | 婚姻

      .col-sm-10
        .radio.radio-inline
          label
            = f.radio_button :marriage, 1, {checked: f.object.marriage == true}
            | 已婚
        .radio.radio-inline
          label
            = f.radio_button :marriage, 0, {checked: f.object.marriage == false}
            | 未婚

    .form-group
      label.col-sm-2.control-label
        | 兵役

      .col-sm-10
        - Interviewee.militaries.each do |military|
          .radio.radio-inline
            label
              = f.radio_button :military, military.first,
                    {checked: f.object.military.to_s == military.first.to_s}
              = t "enums.interviewee.military.#{military.first}"

    .form-group
      label.col-sm-3.control-label
        | 現在本公司服務之親友姓名

      .col-sm-9
        = f.text_field :relatives, class: 'form-control'

    .form-group
      label.col-sm-2.control-label
        | 專長
      .col-sm-10
        = f.text_field :expertise, class: 'form-control'

    .form-group
      label.col-sm-2.control-label
        | 興趣
      .col-sm-10
        = f.text_field :hobby, class: 'form-control'

app/views/pre_interview/_supervisor.html.slim
.panel.panel-default.margin-top-10
  .panel-heading.font-normal
    | 可詢問的前直屬主管
  .panel-body.font-normal
    table.table.table-bordered#supervisor-table
      thead
        tr
          th 姓名
          th 服務單位
          th 職稱
          th 聯絡電話
          th 方便聯絡時間

      tbody
        = f.fields_for :supervisors, wrapper: false do |ff|
          tr.fields
            td
              = ff.hidden_field :id
              = ff.text_field :name, class: 'form-control'
            td = ff.text_field :department, class: 'form-control'
            td = ff.text_field :title, class: 'form-control'
            td = ff.text_field :phone, class: 'form-control'
            td = ff.text_field :contact_time, class: 'form-control'

    = f.link_to_add :supervisors, class: 'btn btn-sm btn-primary', data: {target: "#supervisor-table"} do
      = fa_icon('plus')

app/views/pre_interview/complete.html.slim
.jumbotron.margin-top-10
  h1.text-center 風尚股份有限公司

  h2.text-center
    | 感謝您的填寫！

app/views/pre_interview/consent.html.slim
.panel.panel-default.margin-top-10
  .panel-body.font-normal

    = render partial: 'pre_interview/consent'

    = link_to '同意', pre_interview_new_path, class: 'btn btn-raised btn-primary'

app/views/pre_interview/edit.html.slim
h1.text-center 面試人員資料表

.alert.alert-dismissible.alert-warning
  p
    | 本人鄭重聲明以下所填各項資料均屬事實，並同意貴公司於建立個人資料集合於法令下，得蒐集、利用及處理以下各項資料，且得於本人到職後向資料記載單位諮詢
    | ，如有虛報不實情事願受免職處分。

= nested_form_for @interviewee, url: pre_interview_update_path(params[:token]), html: { class: 'form-horizontal' } do |f|

  = render partial: 'pre_interview/form', locals: {f: f, disabled: true}

  = f.submit class: 'btn btn-primary', value: '送出', data: { confirm: '送出後不能再修改，確定送出嗎？' }

app/views/pre_interview/new.html.slim
h1.text-center 面試人員資料表

.alert.alert-dismissible.alert-warning
  p
    | 本人鄭重聲明以下所填各項資料均屬事實，並同意貴公司於建立個人資料集合於法令下，得蒐集、利用及處理以下各項資料，且得於本人到職後向資料記載單位諮詢
    | ，如有虛報不實情事願受免職處分。

= nested_form_for @interviewee, url: pre_interview_create_path, html: { class: 'form-horizontal' } do |f|

  = render partial: 'pre_interview/form', locals: {f: f, disabled: true}

  = f.submit class: 'btn btn-primary', value: '送出', data: { confirm: '送出後不能再修改，確定送出嗎？' }