config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { passwords: :passwords }

  devise_scope :user do

    get '/users/slack_callback' => 'sessions#slack_callback'

    authenticated :user do
      root 'dashboard#index'
    end
    unauthenticated :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  resources :interviewees, except: [:destroy], concerns: [:paginatable] do
    resources :activities, only: [:index, :create]

    member do
      get :print
    end

    collection do
      get :result
      get :calendar
    end
  end

  resources :positions, except: [:show]
  resources :dashboard, only: [:index]
  resource :user, only: [:edit, :update]

  scope 'pre-interview', controller: 'pre_interview', as: 'pre_interview' do
    get 'consent/', action: :consent, as: 'consent'
    get 'new/', action: :new, as: 'new'
    post 'create/', action: 'create', as: 'create'
    get 'complete', action: 'complete', as: 'complete'
  end

end

app/models/interviewee.rb
class Interviewee < ActiveRecord::Base

  mount_uploader :resume, ResumeUploader

  has_many :educations
  has_many :experiences
  has_many :families
  has_many :supervisors

  accepts_nested_attributes_for :educations,  reject_if: -> (attributes) { attributes[:name].blank? }
  accepts_nested_attributes_for :experiences, reject_if: -> (attributes) { attributes[:name].blank? }
  accepts_nested_attributes_for :families,    reject_if: -> (attributes) { attributes[:name].blank? }
  accepts_nested_attributes_for :supervisors, reject_if: -> (attributes) { attributes[:name].blank? }

  validates :name, :position_id, presence: true
  validates :id_number, format: { with: /\A[A-Z]\d{9}\z/, message: "格式不合" }, if: -> { self.id_number.present? }
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

  enum gender: { female: 0, male: 1 }
  enum status: {
      pending: 0,
      no_response: 1,
      send_email: 9,
      arrange_interview: 10,
      waiting_interview: 2,
      refuse_interview: 3,
      failed: 5,
      admit: 6,
      black: 7,
      abandon: 8
  }
  enum military: {
    military_yet: 1,
    military_finish: 2,
    military_no_need: 3
  }

  belongs_to :position
  has_many :activities, -> { order(created_at: :desc) }

  before_create -> {
    self.status = :pending
    self.token  = SecureRandom.hex(32)
  }

  after_update -> {

    self.activities.create({
        content: "[系統] 狀態修改為" + I18n.t("enums.interviewee.status.#{self.status}")
    })

  }, if: :status_changed?

  def build_all_relations
    self.educations.build  if self.educations.empty?
    self.experiences.build if self.experiences.empty?
    self.families.build    if self.families.empty?
    self.supervisors.build if self.supervisors.empty?
  end

end

app/controllers/interviewees_controller.rb
class IntervieweesController < AdminController

  include Savable

  before_action :set_interviewees, only: [:index, :result, :calendar]
  before_action :set_interviewee_status, only: [:index, :result]

  layout false, only: [:print]

  def index
    params[:status] = params[:status].nil? ? 0 : params[:status]
    @interviewees = @interviewees.where(status: params[:status])
    set_activity_count
  end

  # search result
  def result

    if params[:keyword].blank?
      redirect_to action: :index
    end

    @interviewees = @interviewees.where('name like ? or number = ?', "%#{params[:keyword]}%", params[:keyword])
    set_activity_count
  end

  def calendar
    @interviewees = @interviewees.where(status: Interviewee.statuses[:waiting_interview])

    result = []
    @interviewees.each do |interviewee|

      if interviewee.interview_at.present?
        time = interviewee.interview_at
        obj = {
            event: {
                id: interviewee.id,
                name: "#{interviewee.name} (#{interviewee.position.name})",
                startdate: time.to_s(:date_only),
                enddate: '',
                starttime: time.strftime("%H:%M"),
                endtime: (time + 2.hours).strftime("%H:%M"),
                color: '#e94b35',
                url: result_interviewees_path(keyword: interviewee.number)
            }
        }

        result.push obj
      end

    end

    respond_to do |format|
      format.xml {
        render xml: result
      }
    end

  end

  def print
    set_resource
  end

  private

  def set_empty_resource
    super
    build_relations
  end

  def after_save_failed(exception)
    build_relations
    super
  end

  def after_save_success(param)
    redirect_to interviewees_path status: param['status']
  end

  def set_interviewees
    @interviewees = Interviewee
                      .includes(:position)
                      .page(params[:page])
                      .order(created_at: :desc)
  end

  def set_interviewee_status
    @status = Interviewee.group(:status).count
  end

  def set_activity_count
    @activity_count = Activity.group_count(@interviewees)
  end

  def build_relations
    @interviewee.build_all_relations
  end

  def strong_params
    params.require(:interviewee)
      .permit(:finish_edit, :name, :number, :status, :position_id, :interview_at, :note,
              :name_en, :birthday, :native_place, :id_number, :gender, :blood_type, :communicate_address, :communicate_phone,
              :residence_address, :residence_phone, :email, :phone, :over_time, :marriage, :military, :relatives,
              :expertise, :hobby, :health, :genetic_disease, :genetic_disease_note, :nociceptive_disease,
              :nociceptive_disease_note, :other_disease, :other_disease_note, :chinese, :taiwanese, :hakka, :english,
              :japanese, :onboard_date, :wish_salary, :other_language_familiar, :other_language_unfamiliar,
              educations_attributes: [:id, :name, :department, :graduated, :school_type],
              experiences_attributes: [:id, :name, :title, :period, :seniority, :salary, :reason],
              families_attributes: [:id, :title, :name, :job],
              supervisors_attributes: [:id, :name, :department, :title, :phone, :contact_time]
      )
  end

end

app/views/interviewees/_interviewee.html.slim
.col-md-6
  .panel.panel-default
    .panel-heading
      = link_to edit_interviewee_path(interviewee) do
        = "#{interviewee.name} "
        - if interviewee.gender.present?
          = t("enums.interviewee.gender.#{interviewee.gender}")

      label.label.label-warning[style="margin-left: 20px"]
        = t("enums.interviewee.status.#{interviewee.status}")

      .pull-right
        = fa_icon('calendar')
        '
        = interviewee.created_at.to_s(:date_only)
    table.table.interviewee-table
      tbody
        tr
          th 編號
          td
            = interviewee.number
          th 電話
          td = interviewee.phone
        tr
          th email
          td = mail_to interviewee.email
          th 職缺
          td = interviewee.position.name
        tr
          th 備註
          td[colspan="3"] = interviewee.note
        tr
          th 面試時間
          td
            - if interviewee.interview_at.present?
              = interviewee.interview_at.to_s(:normal)
          td[colspan="2"]
            .pull-right
              - if interviewee.resume_url
                = link_to '履歷下載', interviewee.resume_url, class: 'btn btn-xs btn-info', target: '_blank'
              '
              = button_tag class: 'btn btn-xs btn-success activities',
                           type: :button, "data-id" => interviewee.id do
                | 活動記錄
                - if @activity_count[interviewee.id]
                  '
                  span.badge = @activity_count[interviewee.id]
            .clearfix

app/views/interviewees/_script.html.erb
<script>
  $(function(){
    $(".activities").click(function(){

      $.ajax({
        url: '/interviewees/' + $(this).data('id') + '/activities',
        method: 'GET'
      }).done(function(data){

        bootbox.dialog({
          message: data,
          title: "活動記錄",
          onEscape: function() { },
          backdrop: true,
          buttons: {
            success: {
              label: "關閉",
              className: "btn-default"
            }
          }
        });

      });

    });

    if($("#nav").length) {
      setNavWidth();
      var navWidth = $(".nav-container").width();
      var $activeNav = $("#nav").find('li.active');
      var activeNavOffset = $activeNav.offset().left;

      if(activeNavOffset > navWidth) {
        $(".nav-container").animate({
          scrollLeft: activeNavOffset + $activeNav.outerWidth(true)
        }, 1000);
      }
    }
  });

  var setNavWidth = function() {
    var width = 1;
    $("#nav").find('li').each(function(){
      width += $(this).outerWidth(true);
    });
    $("#nav").width(width);
  }
</script>

app/views/interviewees/form.html.slim
h3 面試人員設定

= nested_form_for @interviewee, html: { class: 'form-horizontal' } do |f|

  = link_to '回上一頁', interviewees_path, class: 'btn btn-raised btn-default'
  = f.submit class: 'btn btn-primary', value: '送出'

  - if in_edit?
    .pull-right
      = link_to '列印', print_interviewee_path, class: 'btn btn-raised btn-default'

  .panel.panel-default.margin-top-10
    .panel-heading.font-normal
      | 管理員使用
    .panel-body.font-normal

      - if in_edit?
        .form-group
          label.col-sm-2.control-label 狀態

          .col-sm-10
            = f.collection_select :position_id, Interviewee.statuses,
                    :first, -> (s) { t("enums.interviewee.status.#{s.first}") },
                    {}, class: 'form-control'

      .form-group
        label.col-sm-2.control-label 已編輯

        .col-sm-10
          .togglebutton
            label
              = f.check_box :finish_edit

      .form-group
        label.col-sm-3.col-md-2.control-label
          | 履歷上傳
        .col-sm-7.col-md-9
          = f.file_field :resume, class: 'form-control'

        - if f.object.resume_url
          .col-md-1.col-sm-2
            = link_to '下載', f.object.resume_url, class: 'btn btn-primary btn-sm', target: '_blank'

      .form-group
        label.col-sm-2.control-label 編號

        .col-sm-10
          = f.text_field :number, class: 'form-control'

      .form-group
        label.col-sm-2.control-label 面試時間

        .col-sm-10
          = f.text_field :interview_at, class: 'form-control datetime-picker'

      .form-group
        label.col-sm-2.control-label 備註

        .col-sm-10
          = f.text_field :note, class: 'form-control'

  = render partial: 'pre_interview/form', locals: {f: f, disabled: false}

/hr

/- if in_edit?

  h3 活動記錄

  = simple_form_for Activity.new, url: interviewee_activities_path(params[:id]),
                    html: { class: 'form-horizontal' } do |f|

    .form-group
      .col-md-10
        = f.text_field :content, class: 'form-control', placeholder: '留言記錄', required: true

      .col-md-2
        = f.submit '送出', class: 'btn btn-primary'

  - if @interviewee.activities.present?
    table.table
      tbody
        - @interviewee.activities.each do |a|
          tr
            td[style="width: 160px"] = a.created_at.to_s(:normal)
            td = a.content

  - else
    .alert.alert-danger[role="alert"]
      span
        = fa_icon('exclamation')
      '
      = t("no_data")

app/views/interviewees/index.html.slim
.row
  .col-md-1.col-sm-2.col-xs-2
    .btn-group
      = link_to new_interviewee_path, class: 'btn btn-primary btn-sm' do
        = fa_icon('plus')

  .col-md-11.col-sm-10.col-xs-10.nav-container
    ul.nav.nav-pills#nav
      - Interviewee.statuses.each do |value, key|
        li[class="#{(params[:status].to_i == key.to_i) ? 'active' : '' }"]
          = link_to interviewees_path(status: key) do
            = t("enums.interviewee.status.#{value}")
            - if @status[key]
              span.badge = @status[key]


.clearfix
br

- if @interviewees.present?
  = render @interviewees

  .row
    .col-md-12
      = paginate @interviewees

- else
  .alert.alert-danger[role="alert"]
    span
      = fa_icon('exclamation')
    '
    = t("no_data")

= render 'script'

app/views/interviewees/print.html.slim
doctype html
html
  head
    meta[http-equiv="X-UA-Compatible" content="IE=edge"]
    meta[name="viewport" content="width=device-width,initial-scale=1"]

    title
      | 面試管理系統
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body

    .container
      .well.font-normal

        h3.text-center.no-margin 風尚數位科技股份有限公司

        h4.text-center 面試人員資料表

        p.text-danger
          | 本人鄭重聲明以下所填各項資料均屬事實，並同意貴公司於建立個人資料集合於法令下，得蒐集、利用及處理以下各項資料，且得於本人到職後向資料記載單位諮詢
          | ，如有虛報不實情事願受免職處分。

        table.table.table-bordered
          tr
            th 中文姓名
            td = @interviewee.name
            th 性別
            td
              - Interviewee.genders.each do |gender|

                label.margin-left-10
                - if gender.first == @interviewee.gender
                  = fa_icon('check-square-o')
                - else
                  = fa_icon('square-o')
                '
                = t("enums.interviewee.sex.#{gender.first}")
            th 應徵項目
            td = @interviewee.position.name
          tr
            th 英文姓名
            td = @interviewee.name_en
            th 出生日期
            td = @interviewee.birthday
            th 籍貫
            td = @interviewee.native_place
          tr
            th 身份證號碼
            td = @interviewee.id_number
            th 血型
            td = @interviewee.blood_type
            th 加班
            td = @interviewee.over_time ? '可' : '否'
          tr
            th 婚姻
            td = @interviewee.marriage ? '已婚' : '未婚'
            th 兵役
            td = t("enums.interviewee.military.#{@interviewee.military}")
            td
            td
          tr
            th 通訊地址
            td[colspan="2"] = @interviewee.communicate_address
            th 電話
            td[colspan="2"] = @interviewee.communicate_phone
          tr
            th 戶籍地址
            td[colspan="2"] = @interviewee.residence_address
            th 電話
            td[colspan="2"] = @interviewee.residence_phone
          tr
            th Email
            td[colspan="2"] = @interviewee.email
            th 行動電話
            td[colspan="2"] = @interviewee.phone

        table.table.table-bordered
          tr
            th 專長
            td = @interviewee.expertise
            th 興趣
            td = @interviewee.hobby
            th 於本公司服務之親友姓名
            td = @interviewee.relatives

        h4 學歷
        table.table.table-bordered
          tr
            th 學校名稱
            th 科系
            th 畢（肄）業
            th 日（夜）間
          - @interviewee.educations.each do |edu|
            tr
              td = edu.name
              td = edu.department
              td = edu.graduated ? '畢業' : '肄業'
              td
                - if edu.school_type == 'day'
                  | 日間
                - elsif edu.school_type == 'night'
                  | 夜間

        h4 經歷
        table.table.table-bordered
          tr
            th 公司名稱
            th 職稱
            th 任職期間
            th 年資
            th 薪資
            th 離職原因
          - @interviewee.experiences.each do |exp|
            tr
              td = exp.name
              td = exp.title
              td = exp.period
              td = exp.seniority
              td = exp.salary
              td = exp.reason
        h4 家庭狀況
        table.table.table-bordered
          tr
            th 稱謂
            th 姓名
            th 職業或就讀學校
          - @interviewee.families.each do |family|
            tr
              td = family.title
              td = family.name
              td = family.job

        h4 健康狀況
        table.table.table-bordered
          tr
            td
              h5.font-normal 過去有否重大疾病

              label.margin-left-10
                = check(@interviewee.health)
                '
                | 否

              label.margin-left-10
                = check(@interviewee.genetic_disease)
                '
                | 遺傳性疾病
                '
                u = @interviewee.genetic_disease_note

              label.margin-left-10
                = check(@interviewee.nociceptive_disease)
                '
                | 傷害性疾病
                '
                u = @interviewee.nociceptive_disease_note

              label.margin-left-10
                = check(@interviewee.other_disease)
                '
                | 其他
                '
                u = @interviewee.other_disease_note

        h4 語言能力
        table.table.table-bordered
          tr
            td 略通
            td
              label.margin-left-10
                = language_check(0, @interviewee.chinese)
                '
                | 國語

              label.margin-left-10
                = language_check(0, @interviewee.taiwanese)
                '
                | 台語

              label.margin-left-10
                = language_check(0, @interviewee.hakka)
                '
                | 客語

              label.margin-left-10
                = language_check(0, @interviewee.english)
                '
                | 英文

              label.margin-left-10
                = language_check(0, @interviewee.japanese)
                '
                | 日文

              label.margin-left-10
                | 其他：
                u = @interviewee.other_language_unfamiliar

          tr
            td 精通
            td
              label.margin-left-10
                = language_check(1, @interviewee.chinese)
                '
                | 國語

              label.margin-left-10
                = language_check(1, @interviewee.taiwanese)
                '
                | 台語

              label.margin-left-10
                = language_check(1, @interviewee.hakka)
                '
                | 客語

              label.margin-left-10
                = language_check(1, @interviewee.english)
                '
                | 英文

              label.margin-left-10
                = language_check(1, @interviewee.japanese)
                '
                | 日文

              label.margin-left-10
                | 其他：
                u = @interviewee.other_language_familiar

        h4 可詢問的前直屬主管
        table.table.table-bordered
          tr
            th 姓名
            th 服務單位
            th 職稱
            th 聯絡電話
            th 方便聯絡時間
          - @interviewee.supervisors.each do |supervisor|
            tr
              td = supervisor.name
              td = supervisor.department
              td = supervisor.title
              td = supervisor.phone
              td = supervisor.contact_time

        table.table.table-bordered
          tr
            th 可到職日
            th 希望待遇
            th 應徵人簽名
          tr
            td = @interviewee.onboard_date
            td = @interviewee.wish_salary
            td

app/views/interviewees/result.html.slim
.row
  .col-md-12
    .btn-group
      = link_to interviewees_path, class: 'btn btn-primary' do
        = fa_icon('caret-left')
        '
        | 回主頁

hr

- if @interviewees.present?
  = render @interviewees
  = paginate @interviewees

- else
  .alert.alert-danger[role="alert"]
    span
      = fa_icon('exclamation')
    '
    = t("no_data")

= render 'script'