config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { passwords: :passwords }

  devise_scope :user do

    get '/users/slack_callback' => 'sessions#slack_callback'

    authenticated :user do
      root 'dashboard#index'
    end
    unauthenticated :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  resources :interviewees, except: [:destroy], concerns: [:paginatable] do
    resources :activities, only: [:index, :create]

    member do
      get :print
    end

    collection do
      get :result
      get :calendar
    end
  end

  resources :positions, except: [:show]
  resources :dashboard, only: [:index]
  resource :user, only: [:edit, :update]

  scope 'pre-interview', controller: 'pre_interview', as: 'pre_interview' do
    get 'consent/', action: :consent, as: 'consent'
    get 'new/', action: :new, as: 'new'
    post 'create/', action: 'create', as: 'create'
    get 'complete', action: 'complete', as: 'complete'
  end

end

app/models/position.rb
class Position < ActiveRecord::Base

  validates :name, presence: true

  has_many :interviewees

end

app/controllers/positions_controller.rb
class PositionsController < AdminController

  include Savable

  def index
    @positions = Position.all
  end

  private

  def strong_params
    params.require('position').permit(:name)
  end

end

app/views/positions/form.html.slim
h3 職缺設定

= simple_form_for @position, html: { class: 'form-horizontal' } do |f|

  = f.input :name, label: '名稱', autofocus: true

  = form_action positions_path

app/views/positions/index.html.slim
h3 職缺設定

= link_to new_position_path, class: 'btn btn-primary' do
  = fa_icon('plus')

table.table.table-bordered.table-striped
  thead
    tr
      th 名稱
  tbody
    - @positions.each do |p|
      tr
        td
          = link_to p.name, edit_position_path(p)