config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { passwords: :passwords }

  devise_scope :user do

    get '/users/slack_callback' => 'sessions#slack_callback'

    authenticated :user do
      root 'dashboard#index'
    end
    unauthenticated :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  resources :interviewees, except: [:destroy], concerns: [:paginatable] do
    resources :activities, only: [:index, :create]

    member do
      get :print
    end

    collection do
      get :result
      get :calendar
    end
  end

  resources :positions, except: [:show]
  resources :dashboard, only: [:index]
  resource :user, only: [:edit, :update]

  scope 'pre-interview', controller: 'pre_interview', as: 'pre_interview' do
    get 'consent/', action: :consent, as: 'consent'
    get 'new/', action: :new, as: 'new'
    post 'create/', action: 'create', as: 'create'
    get 'complete', action: 'complete', as: 'complete'
  end

end

app/views/shares/_nav.html.slim
div.navbar.navbar-default
  .container-fluid
    /! Brand and toggle get grouped for better mobile display
    .navbar-header
      button.navbar-toggle.collapsed aria-expanded="false" data-target="#collapse" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Interview System', root_path, class: 'navbar-brand'
    #collapse.collapse.navbar-collapse
      ul.nav.navbar-nav
        = nav_li '行事曆', dashboard_index_path
        = nav_li '面試狀況', interviewees_path
        = nav_li '職缺設定', positions_path

      ul.nav.navbar-nav.navbar-right
        li.dropdown
          = link_to 'javascript:void(0)', class: 'dropdown-toggle', :"data-toggle" => "dropdown" do
            span
              = current_user.name
            '
            b.caret
          ul.dropdown-menu

            li
              = link_to '編輯', edit_user_path
            li.divider
            li
              = link_to t('page.logout'), destroy_user_session_path, method: :delete

      = form_tag result_interviewees_path, class: 'navbar-form navbar-right', role: :search, method: :get do
        .input-group
          = text_field_tag :keyword, params[:keyword], class: 'form-control', placeholder: 'search'
          .input-group-btn
            = button_tag nil, class: 'btn btn-default', type: :submit do
              = fa_icon('search')

app/views/shares/_toastr.html.erb
<script type="text/javascript" charset="utf-8">

  $(document).on('ready page:load', function() {

    <% unless flash[:alert].nil? %>
    toastr.error('<%= j flash[:alert] %>', 'Error');
    <% end %>

    <% unless flash[:notice].nil? %>
    toastr.info('<%= j flash[:notice] %>', 'Info');
    <% end %>

    <% unless flash[:success].nil? %>
    toastr.success('<%= j flash[:success] %>', 'Success');
    <% end %>

  });

</script>